config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  get "/about", to: "pages#about"

  devise_for :users, controllers: {
    registrations: "registrations",
    sessions: "sessions"
  }

  get "/users/:id", to: "users#show", as: :user
  get "/feed", to: "users#feed", as: :user_feed

  resources :posts do
    resources :comments
  end

  resources :users do
    member do
      get :following, :followers 
    end
  end


  resources :relationships,       only: [:create, :destroy]

  post "/post/:id/like", to: "likes#create", as: :like_post
  delete "/post/:id/like", to: "likes#destroy", as: :unlike_post

  get "/post/:id/reblog", to: "posts#new_reblog", as: :new_reblog
  post "/post/:id/reblog", to: "posts#create_reblog", as: :reblog_post
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: "User"
  has_one :post_note, as: :note, dependent: :destroy
  has_one :post, through: :post_note
  validates :content, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post
  before_action :set_comment, only: [:destroy]

  def new
    @notes = @post.notes
    @comment = @post.comments.build
  end

  def edit
  end

  def create
    @comment = @post.root.comments.create(comment_params.merge(author: current_user))

    if @comment.persisted?
      redirect_to @post
    else
      render :new
    end
  end

  def destroy
    @comment.destroy
    redirect_to @post
  end

  private

  def set_comment
    @comment = @post.comments.find(params[:id])
  end

  def set_post
    @post = Post.find(params[:post_id])
  end

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/views/comments/_comment.html.erb
<div class="card rounded-0 mb-1">
  <div class="card-header p-1">
    <%= render 'shared/profile_picture', user: comment.author %>
    <%= link_to "#{comment.author}", comment.author, class: 'username link' %><span class="text-muted"> wrote <%= time_ago_in_words(comment.created_at) %> ago:</span></small>

    <div class="float-right">
    <% if current_user == comment.author || current_user == @post.author %>
        <%= link_to post_comment_path(@post, comment),
          method: :delete,
          class: "btn btn-outline-danger btn-sm",
          id: "delete-comment-#{comment.id}",
          data: { confirm: "Are you sure you want to delete this comment?" } do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
    <% end %>
    </div>
  </div>
  <div class="card-body px-3 py-2">
    <p class="text-break mb-1"><%= comment.content %></p>
  </div>
</div>

app/views/comments/_form.html.erb
<%= simple_form_for(@comment, url: post_comments_path) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :content, label: "Say something nice:" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Add Comment", class: "btn btn-primary btn-block" %>
  </div>
<% end %>

app/views/comments/new.html.erb
<div class="row">
  <div class="col-md-6 col-sm-12 mx-auto">
    <div class="card mb-4">
      <% @post.ancestors.each do |ancestor| %>
        <%= render 'posts/body', post: ancestor %>
      <% end %>
      <%= render 'posts/body', post: @post %>
      <div class="card-footer text-muted border-top-0">
        <%= render 'comments/form' %>
      </div>
    </div>
  </div>
</div>

<div class="row mb-4">
  <div class="col-md-6 col-sm-12 mx-auto">
    <%= render 'posts/notes' %>
  </div>
</div>