config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  get "/about", to: "pages#about"

  devise_for :users, controllers: {
    registrations: "registrations",
    sessions: "sessions"
  }

  get "/users/:id", to: "users#show", as: :user
  get "/feed", to: "users#feed", as: :user_feed

  resources :posts do
    resources :comments
  end

  resources :users do
    member do
      get :following, :followers 
    end
  end


  resources :relationships,       only: [:create, :destroy]

  post "/post/:id/like", to: "likes#create", as: :like_post
  delete "/post/:id/like", to: "likes#destroy", as: :unlike_post

  get "/post/:id/reblog", to: "posts#new_reblog", as: :new_reblog
  post "/post/:id/reblog", to: "posts#create_reblog", as: :reblog_post
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable

  # validates :username, :email, :password, presence: true
  validates :username, :email, uniqueness: true
  validates :username, format: {with: /\A[a-zA-Z0-9\-]+\z/}, length: {maximum: 32}

  extend FriendlyId
  friendly_id :username, use: :slugged

  has_one_attached :profile_picture
  has_many :posts, foreign_key: :author_id
  has_many :likes, dependent: :destroy
  has_many :comments, foreign_key: :author_id, dependent: :destroy

  has_many :active_relationships, class_name: "Relationship",
                                  foreign_key: "follower_id", 
                                  dependent: :destroy

  has_many :passive_relationships, class_name: "Relationship",
                                  foreign_key: "followed_id", 
                                  dependent: :destroy

  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  def to_s
    if deleted_at
      "[deleted]"
    else
      username
    end
  end

  def soft_delete
    update_attribute(:deleted_at, Time.current)
    comments.destroy_all
    likes.destroy_all
  end

  def active_for_authentication?
    super && !deleted_at
  end

  def inactive_message
    !deleted_at ? super : :invalid
  end

  def follow(other_user)
    following << other_user unless self == other_user
  end

  def unfollow(other_user)
    following.delete(other_user)
  end

  def following?(other_user)
    following.include?(other_user)
  end

  def feed
    following_ids = "SELECT followed_id FROM relationships WHERE follower_id = :user_id"
    @posts = Post.where("author_id IN (#{following_ids}) OR author_id = :user_id", user_id: id).order(created_at: :desc)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :not_found
  before_action :set_user, only: [:show, :followers, :following]

  def show
    if @user.deleted_at
      not_found
    else
      @posts = @user.posts.order(created_at: :desc)
    end
  end

  def not_found
    render :not_found
  end

  def followers
    @title = "Followers"
    @users = @user.followers
    render 'show_follow'
  end

  def following
    @title = "Following"
    @users = @user.following
    render 'show_follow'
  end

  def feed
    @posts = current_user.feed
  end

  private 

    def set_user
      @user = User.friendly.find(params[:id])
    end
end

app/views/users/_follow.html.erb
<%= form_with(model: current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_profile_card.html.erb
<div class="row mb-1">
  <div class="col-md-6 col-sm-12 mx-auto">
    <div class="card">
      <div class="card-body">
        <div class="row">
          <div class="col-4">
            <% if user.profile_picture.attached? %>
              <%= image_tag user.profile_picture.variant(resize: "180x150^", crop: '180x180+0+0').processed, class: 'card-img', id: 'profile-picture' %>
            <% end %>
          </div>
          <div class="col-8">
            <h3 class="card-title"><%= user.username %></h3>
            <p><%= user.bio %></p>
            <a href="<%= following_user_path(@user) %>">
              <strong id="following" class="stat">
                <%= @user.following.count %>
              </strong>
            following
            </a>
            <a href="<%= followers_user_path(@user) %>">
              <strong id="followers" class="stat">
                <%= @user.followers.count %>
              </strong>
            followers
            </a>
            <% if user_signed_in? %>
              <% unless user == current_user %>
                <div id="follow_form">
                  <% if current_user&.following?(@user) %>
                    <%= render 'unfollow' %>
                  <% else %>
                    <%= render 'follow' %>
                  <% end %>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<% if user == current_user %>
  <div class="row mb-1">
    <div class="col-md-6 col-sm-12 mx-auto">
      <div class="btn-group btn-block">
        <%= link_to new_post_path, class: "btn btn-primary" do %>
          <i class="fas fa-edit"></i> New Post
        <% end %>
        <%= link_to edit_user_registration_path(@user), class: 'btn btn-success' do %>
          <i class="fas fa-user-edit"></i> Edit Profile
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_with(model: current_user.active_relationships.find_by(followed_id: @user.id),
              html: { method: :delete }, remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-secondary" %>
<% end %>

app/views/users/feed.html.erb
<div class="row mt-4">
  <div class="col-md-6 col-sm-12 mx-auto">
    <% @posts.each do |post| %>
      <%= render 'posts/thread', thread: post.path %>
    <% end %>
  </div>
</div>

app/views/users/not_found.html.erb
<div class="row">
  <div class="col-5 mx-auto">
    <h1>There's nothing here.</h1>
    <%= image_tag('404.gif') %>
  </div>
</div>

app/views/users/show.html.erb
<%= render 'users/profile_card', user: @user %>

<div class="row mt-4">
  <div class="col-md-6 col-sm-12 mx-auto">
    <% @posts.each do |post| %>
      <%= render 'posts/thread', thread: post.path %>
    <% end %>
  </div>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row mt-4">
  <div class="col-md-6 col-sm-12 mx-auto">
    <div class="card">
      <div class="card-header"><%= @title %></div>
      <ul class="list-group list-group-flush">
        <% @users.each do |user| %>
          <a href="<%= user_path(user) %>" class="list-group-item list-group-item-action">
            <div style="display: inline-block; vertical-align: top;" class="mr-2">
              <% if user.profile_picture.attached? %>
                <%= image_tag user.profile_picture.variant(resize: "60x60").processed, style: "border-radius: 4px;" %>
              <% end %>
            </div>
            <div style="display: inline-block;">
              <h3 class="mb-0"><%= user %></h3>
              <p class="mb-0"><%= user.bio %></p>
            </div>
          </a>
        <% end %>
      </ul>
    </div>
  </div>
</div>