config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  get "/about", to: "pages#about"

  devise_for :users, controllers: {
    registrations: "registrations",
    sessions: "sessions"
  }

  get "/users/:id", to: "users#show", as: :user
  get "/feed", to: "users#feed", as: :user_feed

  resources :posts do
    resources :comments
  end

  resources :users do
    member do
      get :following, :followers 
    end
  end


  resources :relationships,       only: [:create, :destroy]

  post "/post/:id/like", to: "likes#create", as: :like_post
  delete "/post/:id/like", to: "likes#destroy", as: :unlike_post

  get "/post/:id/reblog", to: "posts#new_reblog", as: :new_reblog
  post "/post/:id/reblog", to: "posts#create_reblog", as: :reblog_post
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-light bg-light py-0 border-bottom">
  <div class="container-fluid">
    <%= link_to "rumblr", root_path, class: "navbar-brand" %>
    <div class="dropdown"> <button class="btn btn-outline-secondary btn-sm dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Menu</button>
      <div class="dropdown-menu dropdown-menu-right">
          <% if user_signed_in? %>
            <%= link_to 'Dashboard', user_feed_path, class: "dropdown-item" %>
            <%= link_to 'New post', new_post_path, class: "dropdown-item" %>
            <%= link_to 'View profile', user_path(current_user), class: "dropdown-item" %>
            <%= link_to 'Edit profile', edit_user_registration_path(current_user), class: "dropdown-item" %>
            <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          <% else %>
            <%= link_to "Sign up", new_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Log in", new_user_session_path, class: "dropdown-item" %>
          <% end %>
      </div>
    </div>
  </div>
</nav>

app/views/shared/_profile_picture.html.erb
<% if user.profile_picture.attached? && user.deleted_at.nil? %>
    <%= image_tag user.profile_picture.variant(resize: "20x20^", crop: '20x20+0+0').processed, class: 'img-thumbnail' %>
<% else %>
  <%= image_tag 'https://via.placeholder.com/20', class: 'img-thumbnail' %>
<% end %>