config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  get "/about", to: "pages#about"

  devise_for :users, controllers: {
    registrations: "registrations",
    sessions: "sessions"
  }

  get "/users/:id", to: "users#show", as: :user
  get "/feed", to: "users#feed", as: :user_feed

  resources :posts do
    resources :comments
  end

  resources :users do
    member do
      get :following, :followers 
    end
  end


  resources :relationships,       only: [:create, :destroy]

  post "/post/:id/like", to: "likes#create", as: :like_post
  delete "/post/:id/like", to: "likes#destroy", as: :unlike_post

  get "/post/:id/reblog", to: "posts#new_reblog", as: :new_reblog
  post "/post/:id/reblog", to: "posts#create_reblog", as: :reblog_post
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, unless: -> { content.present? || ancestry? }
  validates :content, presence: true, unless: -> { title.present? || ancestry? }
  belongs_to :author, class_name: "User"
  has_ancestry
  has_many :post_notes, dependent: :destroy
  has_many :comments, through: :post_notes, source: :note, source_type: "Comment"
  has_many :likes, through: :post_notes, source: :note, source_type: "Like"

  def empty_reblog?
    !title.present? && !content.present?
  end

  def notes
    root.post_notes.order(created_at: :desc).map(&:note)
  end

  def thread
    path
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
  before_action :authorize_user, only: [:edit, :update, :destroy]

  def index
    @posts = Post.all.order(created_at: :desc)
  end

  def show
    @comments = @post.comments.order(created_at: :desc)
  end

  def new
    @post = current_user.posts.build
  end

  def edit
    if current_user != @post.author
      redirect_to @post, notice: "That doesn't belong to you."
    end
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      redirect_to current_user, notice: "Post was successfully created."
    else
      render :new
    end
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: "Post was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to current_user, notice: "Post was successfully destroyed."
  end

  def new_reblog
    @parent = Post.find(params[:id])
    @post = @parent.children.build(author: current_user)
  end

  def create_reblog
    @parent = Post.find(params[:id])
    @post = @parent.children.build(post_params)
    @post.author = current_user

    if @post.save
      @note = PostNote.create(post_id: @parent.root.id, note_id: @post.id, note_type: "Post")
      redirect_to @post
    else
      render :new_reblog
    end
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :content, :parent_id)
  end

  def authorize_user
    current_user == @post.author
  end
end

app/views/posts/_author_buttons.html.erb
<% if current_user == post.author %>
  <%= link_to edit_post_path(post), 
    class: "btn btn-outline-success btn-sm",
    id: "edit-#{post.id}" do %>
    <i class="fas fa-pencil-alt"></i>
  <% end %>
  <%= link_to post_path(post), 
    method: :delete, 
    class: "btn btn-outline-secondary btn-sm",
    id: "delete-#{post.id}",
    data: { confirm: "Are you sure you want to delete this post?" } do %>
    <i class="fas fa-trash-alt"></i>
  <% end %>
<% end %>

app/views/posts/_body.html.erb
<div class="card-body border-bottom px-2 pt-0">
  <% if post.title %>
    <h4 class="post-title"><%= post.title %></h4>
  <% end %>
  <%= post.content %>
</div>

app/views/posts/_footer.html.erb
<div class="card-footer text-muted border-top-0 p-1">
    <%= render 'posts/time_and_notes', post: post %>
  <div class="float-right">
    <% if user_signed_in? %>
      <%= render 'posts/interaction_buttons', post: post %>
      <%= render 'posts/author_buttons', post: post %>
    <% end %>
  </div>
</div>

app/views/posts/_form.html.erb
<%= simple_form_for(@post) do |f| %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :content %> 
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary btn-block" %>
  </div>
<% end %>

app/views/posts/_interaction_buttons.html.erb
<%= link_to new_reblog_path(post),
  id: "reblog-#{post.id}",
  class: 'btn btn-outline-primary btn-sm' do %>
  <i class="fas fa-retweet"></i>
<% end %>

<%= link_to new_post_comment_path(post), 
  id: "comment-#{post.id}",
  class: 'btn btn-outline-primary btn-sm' do %>
  <i class="far fa-comment"></i>
<% end %>
<span id="like-unlike-<%= post.id %>">
  <% like = post.root.likes.find { |like| like.user == current_user } %>
  <% if like %>
    <%= render 'posts/unlike_button', post: post, like: like %>
  <% else %>
    <%= render 'posts/like_button', post: post %>
  <% end %>
</span>

app/views/posts/_like_button.html.erb
<% if user_signed_in? %>
  <%= link_to like_post_path(post),
    method: :post,
    remote: true,
    class: "btn btn-outline-danger btn-sm",
    id: "like-#{post.id}" do %>
    <i class="far fa-heart"></i>
  <% end %>
<% end %>

app/views/posts/_notes.html.erb
<% @post.notes.each do |note| %>
  <% if note.class == Post %>
    <% if note.empty_reblog? %>
      <%= render 'notes/empty_reblog', reblog: note %>
    <% else %>
      <%= render 'posts/reblog', reblog: note %>
    <% end %>
  <% else %>
    <%= render note %>
  <% end %>
<% end %>

<%= render 'notes/note_header', 
  user: @post.root.author,
  action: "posted this.",
  link: @post.root %>

app/views/posts/_post.html.erb
<%= render 'posts/header', post: post %>
<%= render 'posts/body', post: post %>
<%= render 'posts/footer', post: post %>

app/views/posts/_post_header.html.erb
<div style="padding: 0.5em; display: inline-block; vertical-align: top;" class="mr-2">
  <% if post.author.profile_picture.attached? %>
    <%= image_tag post.author.profile_picture.variant(resize: "25x25").processed, style: "margin-right: 0.25em; border-radius: 2px;" %>
  <% end %>
  <strong><%= link_to "#{post.author}", post.author, class: 'post.authorname link' %></strong>
</div>

app/views/posts/_reblog.html.erb
<div class="card my-1 rounded-0">
  <%= render 'notes/note_header', 
    user: reblog.author,
    action: "reblogged this and wrote:",
    link: reblog %>
  <div class="card-body p-2">
    <p class="text-break mb-1"><%= sanitize(truncate(reblog.content, omission: "...", length: 150)) %></p>
  </div>
</div>

app/views/posts/_thread.html.erb
<div class="row my-4">
  <div class="col-12 mx-auto">
    <div class="card" id="thread">
      <%= render('posts/thread_header', post: thread.last) if thread.size > 1 %>
      <% thread.each do |post| %>
        <% unless post.empty_reblog? %>
          <%= render 'posts/post_header', post: post %>
          <%= render 'posts/body', post: post %>
        <% end %>
      <% end %>
      <%= render 'posts/footer', post: thread.last %>
    </div>
  </div>
</div>

app/views/posts/_thread_header.html.erb
<div class="card-header border-bottom p-1">
  <%= render 'shared/profile_picture', user: post.author %>
  <%= link_to "#{post.author}", post.author, class: 'username link' %> reblogged this
  <%= time_ago_in_words(post.created_at) %> ago:</small>
</div>

app/views/posts/_unlike_button.html.erb
<% if user_signed_in? %>
  <%= link_to unlike_post_path(post),
    method: :delete,
    remote: true,
    class: 'btn btn-danger btn-sm',
    id: "unlike-#{post.id}" do %>
      <i class="far fa-heart"></i>
  <% end %>
<% end %>

app/views/posts/index.html.erb
<div class="row mt-4">
  <div class="col-md-6 col-sm-12 mx-auto">
    <% @posts.each do |post| %>
      <%= render 'posts/thread', thread: post.path %>
    <% end %>
  </div>
</div>